CREATE TABLE KhachHang(  
    ID_KH VARCHAR(255) PRIMARY KEY,  
    TenKH VARCHAR(255) NOT NULL,
    SDT VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL, 
    GioiTinh VARCHAR(255) NOT NULL,
    DiaChi VARCHAR(255) NOT NULL,  
   );

CREATE TABLE NhaCungCap (  
    ID_NCC  VARCHAR(255) PRIMARY KEY,  
    Ten_NCC VARCHAR(255) NOT NULL,  
    Email VARCHAR(255) NOT NULL,  
    SDT VARCHAR(255) NOT NULL,  
    DiaChi VARCHAR(255) NOT NULL,  
); 

CREATE TABLE SanPham (  
    ID_SP VARCHAR(255) PRIMARY KEY,  
    Ten_SP VARCHAR(255) NOT NULL,  
    Gia MONEY NOT NULL,
    TheLoai VARCHAR(255) NOT NULL,
    MoTa VARCHAR(255) NOT NULL,
    SoLuong INT NOT NULL,  
    ID_NCC VARCHAR(255),
    FOREIGN KEY (ID_NCC) REFERENCES NhaCungCap(ID_NCC),  
); 
   
CREATE TABLE ChiNhanh(
     ID_ChiNhanh VARCHAR(255) PRIMARY KEY,
     TenChiNhanh VARCHAR(255) NOT NULL,
     Email VARCHAR(255) NOT NULL,
     DiaChi VARCHAR(255) NOT NULL,
     SDT VARCHAR(255) NOT NULL
);

CREATE TABLE NhanVien (  
    ID_NV VARCHAR(255) PRIMARY KEY,  
    TenNV VARCHAR(255) NOT NULL,  
    ChucVu VARCHAR(255) NOT NULL,  
    NgaySinh DATE NOT NULL,  
    GioiTinh VARCHAR(255) NOT NULL, 
    ID_ChiNhanh VARCHAR(255) NOT NULL
    FOREIGN KEY ( ID_ChiNhanh) REFERENCES ChiNhanh( ID_ChiNhanh) 
);  

CREATE TABLE TruSoChinh(
     ID_TSC VARCHAR(255) PRIMARY KEY,
     ID_ChiNhanh VARCHAR(255) NOT NULL,
     TenTSC VARCHAR(255) NOT NULL,
     Email VARCHAR(255) NOT NULL,
     DiaChi VARCHAR(255) NOT NULL,
     SDT VARCHAR(255) NOT NULL,
     FOREIGN KEY (ID_ChiNhanh ) REFERENCES ChiNhanh(ID_ChiNhanh )
);

CREATE TABLE GiaoDich(  
    ID_GD VARCHAR(255) PRIMARY KEY,  
    ID_KH VARCHAR(255) NOT NULL, 
    ID_SP VARCHAR(255) NOT NULL, 
    ID_NV VARCHAR(255) NOT NULL,
    ID_ChiNhanh  VARCHAR(255) NOT NULL,
    ThoiGian DATE NOT NULL,  
    SoLuong VARCHAR(255) NOT NULL,  
    TongTien MONEY NOT NULL,
    FOREIGN KEY (ID_KH ) REFERENCES KhachHang(ID_KH),
    FOREIGN KEY (ID_SP) REFERENCES SanPham(ID_SP), 
    FOREIGN KEY ( ID_NV) REFERENCES NhanVien( ID_NV),
    FOREIGN KEY ( ID_ChiNhanh) REFERENCES ChiNhanh( ID_ChiNhanh) 
);  

