ALTER DATABASE QuanLyNhanSu
COLLATE Latin1_General_CI_AS;

CREATE TABLE TruSoChinh(
ID_TruSoChinh VARCHAR(255),
TenTruSoChinh VARCHAR(255),
DiaChi VARCHAR(255),
Email VARCHAR(255),	
SoDienThoai VARCHAR(255),
PRIMARY KEY(ID_TruSoChinh)
);

CREATE TABLE ChinhSach(
ID_ChinhSach VARCHAR(255),
TenChinhSach VARCHAR(255),
MoTa VARCHAR(255),
PRIMARY KEY(ID_ChinhSach),
);
CREATE TABLE ChiNhanh(
ID_ChiNhanh VARCHAR(255),
ID_TruSoChinh VARCHAR(255),
ID_ChinhSach VARCHAR(255),
TenChiNhanh VARCHAR(255),
DiaChi VARCHAR(255),
Email VARCHAR(255),	
SoDienThoai VARCHAR(255),
PRIMARY KEY(ID_ChiNhanh),
FOREIGN KEY(ID_TruSoChinh) REFERENCES TruSoChinh(ID_TruSoChinh),
FOREIGN KEY(ID_ChinhSach) REFERENCES ChinhSach(ID_ChinhSach)
);


CREATE TABLE PhongBan(
ID_PhongBan VARCHAR(255),
ID_ChiNhanh VARCHAR(255),
TenPhongBan VARCHAR(255),
Email VARCHAR(255),
SoDienThoai VARCHAR(255),
PRIMARY KEY(ID_PhongBan),
FOREIGN KEY(ID_ChiNhanh) REFERENCES ChiNhanh(ID_ChiNhanh)
);

CREATE TABLE DuAn(
ID_DuAn VARCHAR(255),
ID_PhongBan VARCHAR(255),
TenDuAn VARCHAR(255),
NgayBatDau DATE,
ThoiHan INT,
MoTa VARCHAR(255),
PRIMARY KEY(ID_DuAn),
FOREIGN KEY(ID_PhongBan) REFERENCES PhongBan(ID_PhongBan)
);

CREATE TABLE ChucVu(
ID_ChucVu VARCHAR(255),
ID_ChiNhanh VARCHAR(255),
TenChucVu VARCHAR(255),
BacLuong INT,
PRIMARY KEY(ID_ChucVu),
FOREIGN KEY(ID_ChiNhanh) REFERENCES ChiNhanh(ID_ChiNhanh)
);

CREATE TABLE NhanVien(
ID_NhanVien VARCHAR(255),
ID_DuAn VARCHAR(255),
ID_ChucVu VARCHAR(255),
ID_ChiNhanh VARCHAR(255),
ID_PhongBan VARCHAR(255),
HoTen VARCHAR(255),
NgaySinh DATE,
GioiTinh VARCHAR(255),
DanToc VARCHAR(255),
CCCD VARCHAR(255),
SoDienThoai VARCHAR(255),
Email VARCHAR(255),	
DiaChi VARCHAR(255),
PRIMARY KEY(ID_NhanVien),
FOREIGN KEY(ID_DuAn) REFERENCES DuAn(ID_DuAn),
FOREIGN KEY(ID_ChucVu) REFERENCES ChucVu(ID_ChucVu),
FOREIGN KEY(ID_ChiNhanh) REFERENCES ChiNhanh(ID_ChiNhanh),
FOREIGN KEY(ID_PhongBan) REFERENCES PhongBan(ID_PhongBan),
);

CREATE TABLE Luong(
ID_Luong VARCHAR(255),
ID_NhanVien VARCHAR(255),
MucLuong INT,
PRIMARY KEY(ID_Luong),
FOREIGN KEY(ID_NhanVien) REFERENCES NhanVien(ID_NhanVien)
);

